### ISSUE TITLE
Support older cameras that send MJPEG over RTSP

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#101]
Customer's report:

The DCL-932L video screen is mostly green with garbage across the top. This error shows in relation to the camera that doesn't work, "Video stream timebase is unusual"

Viewing the camera on a browser from the URL and path defined in Bluecherry config work fine.

Aug 18 20:31:56 scar bc-server[1594]: I(8/Walkway): Setting up device

Aug 18 20:31:56 scar bc-server[1594]: I(8/Walkway): Video stream timebase is unusual (1/1200000). This could cause timing issues.

Aug 18 20:31:56 scar bc-server[1594]: I(8/Walkway): Stream started: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 1/1200000(s) 1/25(c)

http://community.bluecherrydvr.com/topic/d-lin-dcs-932l-video-stream-timebase-is-unusual

**Comment by ghost** [comment]
There was no access provided. If somebody provides access to camera, we'll be able to investigate this. "Video stream timebase is unusual" warning is not related to the screen being green garbage.
