### ISSUE TITLE
Web: Allow user to change default from address in emails

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#102]
This has been reported several times, the default 'from' address is donotreply@bluecherryserver.  Most SMTP servers won't allow any emails to be sent with this address.  

This is currently hard coded into /usr/share/bluecherry/www/lib/mailer.php (https://github.com/bluecherrydvr/bluecherry-apps/blob/master/www/lib/mailer.php#L115) and needs to be a option in General Settings for the SMTP setup.

**Comment by curtishall** [comment]
https://secure.helpscout.net/conversation/116783222/6278/

**Comment by Aleksandern** [comment]
done in issue102 branch
