### ISSUE TITLE
Option for continous or motion detection is missing from global and per-device areas

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#113]
https://s3.amazonaws.com/uploads.hipchat.com/13776/47773/ptv2w2B1gjJnDJQ/upload_thumb.png

https://s3.amazonaws.com/uploads.hipchat.com/13776/47773/t1dPffEeDD0VqxJ/upload_thumb.png

**Comment by andrey-utkin** [comment]
Fixed by PR https://github.com/bluecherrydvr/bluecherry-apps/pull/268 , included to v2.5.13.
