### ISSUE TITLE
Unable to add storage in web UI (bug in permission checking)

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#132]
As discussed..

1) group writable perm is not actually needed
2) the check is still too much rigid, it checks against 770 and won't allow other permissions (www/ajax/storagecheck.php)

perms should be compared bitwise

If a customer wants 777 or some other permissions that allow world read access put a notice to the web ui that the permissions are insecure but allow it anyway.

**Comment by antonsviridenko** [comment]
fixed in https://github.com/bluecherrydvr/bluecherry-apps/commit/c538e855e0a4b5e57dafe345ef17d96e7985d18f
