### ISSUE TITLE
Remove non-fatal errors (error writing frame, etc)

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#135]
These are non-fatal errors but customers see the and naturally thing something is wrong.  We need to suppress these warnings.

Jul 26 18:14:37 vidsec bc-server[1170]: E(1/Bar Front): Error writing frame to recording: Invalid argument
Jul 26 18:14:37 vidsec bc-server[1170]: E(1/Bar Front): Failure in recording writing

**Comment by antonsviridenko** [comment]
Error is not fatal, but it causes frames to be skipped from recordings

**Comment by antonsviridenko** [comment]
These errors were caused by wrong timestamps sometimes coming in audio or video streams from some cameras. As a workaround, such timestamps are replaced with (previous timestamp + 1) before writing to recording. Fix will appear in bluecherry server v2.7.9
