### ISSUE TITLE
Unable to download Database backup from the client

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#152]
QtWebKit probably doesn't support file downloads.  We need to detect if they are using the client and prompt them to use a "real" web browser or see if a new version of QtWebKit supports this.

**Comment by curtishall** [comment]
https://bluecherry.freshdesk.com/helpdesk/tickets/1500

**Comment by antonsviridenko** [comment]
I think it's better to start normal browser when menu item "Configure Server" is selected. Why was QtWebKit used here in the first place?

**Comment by curtishall** [comment]
So we didn't have to worry about browser configuration problems (internet explorer, safari, etc)

**Comment by antonsviridenko** [comment]
but if server config page is opened by external browser, authentication will be requested again

now QtWebKit browser window shares cookies received from server after client authentication

**Comment by curtishall** [comment]
It's up to you, if you want to start launching a web browser to access the configuration we can try it in an unstable version for a while, see what customers think

**Comment by antonsviridenko** [comment]
https://github.com/bluecherrydvr/bluecherry-client/commit/06ff5393b0da6add197ecca03b0d018db7e5e2be
