### ISSUE TITLE
Invalid logrotate user, Debian

### ISSUE THREAD

**Issue by ozark-tech** [bluecherrydvr/bluecherry-apps-issues#157]
Debian doesn't ship with 'syslog' user. This prevents the logrotate job from happening out of the box. Either the 'syslog' user should be created at install or /etc/logrotate.d/bluecherry script should be changed to use a default user (such as 'root') or 'bluecherry' for creation:
<pre>
/var/log/bluecherry.log
{
   rotate 7
   daily
   missingok
   notifempty
   delaycompress
   compress
   create 640 **{syslog > root|bluecherry|etc}** bluecherry
   postrotate
      reload rsyslog >/dev/null 2>&1 || true
   endscript
}
</pre>
Note: This is my first bug report ever. Hope it's up to code ;)

**Comment by rstanca** [comment]
Thanks for reporting this! We'll release a fix in a future version of Bluecherry.
