### ISSUE TITLE
Add ONVIF support

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#21]
<a href="https://github.com/curtishall"><img src="https://avatars.githubusercontent.com/u/331478?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [curtishall](https://github.com/curtishall)**
_Mon Aug 26 19:35:49 2013_
_Originally opened as https://github.com/bluecherrydvr/bluecherry-apps/issues/100_

---

ONVIF is a standard that allows cameras to be detected and configured in a universal way.  Links are below:

http://www.onvif.org/
http://www.openipcam.com/forum/index.php/topic,155.0.html
http://en.wikipedia.org/wiki/Open_Network_Video_Interface_Forum

**Comment by ghost** [comment]
Just an update: backend support is included since long time ago. Need web UI pages to operate available tools (devices discovery etc.)
