### ISSUE TITLE
web: client config interface shows like to live view

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#25]
<a href="https://github.com/abelykh"><img src="https://avatars.githubusercontent.com/u/623833?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abelykh](https://github.com/abelykh)**
_Thu Dec 12 15:49:01 2013_
_Originally opened as https://github.com/bluecherrydvr/bluecherry-apps/issues/140_

---

subj

**Comment by curtishall** [comment]
@abelykh I'm confused, what are you talking about on this issue?

**Comment by ghost** [comment]
Uncomprehensible what is meant. Closed.
