### ISSUE TITLE
Warnings "Cannot set motion thresholds (wrong configuration field?)"

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#30]
<a href="https://github.com/krieger-od"><img src="https://avatars.githubusercontent.com/u/803351?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krieger-od](https://github.com/krieger-od)**
_Wed Mar 19 17:12:49 2014_
_Originally opened as https://github.com/bluecherrydvr/bluecherry-apps/issues/165_

---

This happens for V4L2 cameras.
I guess that means that here https://github.com/bluecherrydvr/bluecherry-apps/blob/master/server/bc-thread.cpp#L421 the code sets motion detection threshold for both conventional motion processor and for v4l2_device object, and motion_processor expects motion threshold string of another length, exactly 32*24=768, but for PAL V4L2 camera DB stores 396 chars.

Need a test environment to trace code execution.

This bug is reported by Ami Aronzon.

**Comment by ghost** [comment]
This warning indicates incompatibility of bc-server and solo6x10\* driver.
