### ISSUE TITLE
motion_processor & motion_hander race condition for packet flags

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#42]
<a href="https://github.com/krieger-od"><img src="https://avatars.githubusercontent.com/u/803351?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krieger-od](https://github.com/krieger-od)**
_Wed Jul  2 14:45:06 2014_
_Originally opened as https://github.com/bluecherrydvr/bluecherry-apps/issues/229_

---

`motion_processor` modifies packets `flags` in parallel to `motion_handler` working on them. This may lead to "false negatives" - the cases when frame has motion, but the actual motion flag value not taken into consideration, because it is checked early. This issue doesn't manifest itself (at last in obvious ways) because current implementation of motion_handler traverses packets of GOP again and again while packets add up in current GOP. For issue #86, this approach will be changed, and with new approach the issue manifests itself - detected motion doesn't cause recording start.

**Comment by ghost** [comment]
This illustrates the current state of "continuous" and "motion" modes: https://github.com/bluecherrydvr/bluecherry-apps/blob/motion%2Bcontinuous/server/bc-thread.cpp#L168

**Comment by ghost** [comment]
Fixed in 1e2de935c589479697f8bce3e61175f24dece782 , fix released in v2.3.18.
