### ISSUE TITLE
Strictly limit max age of stored recordings

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#45]
<a href="https://github.com/krieger-od"><img src="https://avatars.githubusercontent.com/u/803351?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krieger-od](https://github.com/krieger-od)**
_Tue Aug  5 15:02:02 2014_
_Originally opened as https://github.com/bluecherrydvr/bluecherry-apps/issues/232_

---

Some legislations forbid storing recordings for longer than 30 days. Need to comply with such requirements. For now we recommend to use crontab script removing old files.

**Comment by ghost** [comment]
Need to update web interface to support backend changes in commit babd8e7a1dac9fb2d547bd0b9ecc3263fefce9fb.

**Comment by curtishall** [comment]
See if Mauren can do this?

**Comment by ghost** [comment]
- replace UPDATE query with INSERT or UPDATE, because setting is absent before first settings tuning in web UI.
- in case of value "0", don't log error, but behave like there's no limit

**Comment by ghost** [comment]
WIP on web UI is in branch max_rec_age

**Comment by ghost** [comment]
Merged in as commit b21f1ad9b872bf6546b586421507205c71d80918 (today).
