### ISSUE TITLE
More useful error code messages for IP cameras

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#52]

**Comment by ghost** [comment]
https://ffmpeg.org/pipermail/ffmpeg-devel/2014-September/163057.html raised the discussion about too abstract error codes

**Comment by ghost** [comment]
Have just submitted a patchset, see "[PATCH 0/5] Add HTTP/RTSP specific AVERROR codes" in ffmpeg-devel. Waiting for its review from ffmpeg core developers.

**Comment by ghost** [comment]
3 of 5 patches in that patchset are already merged upstream.
TODO:
- add exact representation of such conditions as "connection fefused", "host is unreachable"
- make server package builds with all improvements on this issue even before they are merged upstream.

**Comment by ghost** [comment]
5/5 patches were accepted upstream.
Prepared and submitted two more patches on this topic:
[PATCH 1/2] rtsp: pass return code from ffurl_open() on its failure
[PATCH 2/2] http: pass return code from http_open_cnx_internal() on its failure

**Comment by ghost** [comment]
All patches merged.
Updated ffmpeg is used in server package since v2.3.12 release.
@anton Using updated ffmpeg for client app is recommended (you can use https://github.com/bluecherrydvr/ffmpeg repo).
