### ISSUE TITLE
Notify user if system / cameras are offline

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#53]

**Comment by curtishall** [comment]
http://community.bluecherrydvr.com/responses/dvr-system-alert-for-failed-dvr-processes-and-driver-errors

If an analog camera can't be opened (ie - driver not loaded), then email the Administrator immediately and repeat the email atleast once a day

**Comment by ghost** [comment]
2.2.4 version must have such feature available (Device status notifications). It was not tested with analog cameras. Will test.
There's such a point that user has to enable email notifications explicitly, also i find that web UI page not quite intuitive (to enable email notifications at all, you must add a rule (not quite trivial thing).

**Comment by ghost** [comment]
Indeed the issue reproduces. If solo6x10{,_edge} driver is not loaded, then solo_ready variable is never set to true, and analog device contexts are never created, thus no such error condition is triggered, and no notifications are produced. Working on solution.

**Comment by ghost** [comment]
The work in progress is here: https://github.com/bluecherrydvr/bluecherry-apps/tree/enhance_dev_fail_notif
When init of camera connected to solo card fails, it is retried every 8 seconds, so notifications are sent unpleasantly frequently, need to do something about it.

**Comment by ghost** [comment]
Implemented in v2.3.11.
