### ISSUE TITLE
solo_fix_with_newest_kernel: fix regression: "Error setting format" on framerate change

### ISSUE THREAD

**Issue by ghost** [bluecherrydvr/bluecherry-apps-issues#63]
Nov 15 13:46:46 cctvDVR bc-server[127069]: I(1/Port 1 on Card 1): Applying configuration changes
Nov 15 13:46:46 cctvDVR bc-server[127069]: W(1/Port 1 on Card 1): Error setting format
Nov 15 13:46:46 cctvDVR bc-server[127069]: E(1/Port 1 on Card 1): V4L2 device /dev/video1 requested to start, but it failed to initialize
Nov 15 13:46:46 cctvDVR bc-server[127069]: E(1/Port 1 on Card 1): Error starting device stream: 
Nov 15 13:46:46 cctvDVR bc-server[127069]: E(1/Port 1 on Card 1): V4L2 device /dev/video1 requested to start, but it failed to initialize

**Comment by antonsviridenko** [comment]
fix should appear in 2.8.0
