### ISSUE TITLE
Apache non fatal error: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/bluecherry.conf:2

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#67]
Small fix required for this so customers aren't freaking out with this message

**Comment by ghost** [comment]
Should be fixed as of commit e0aa22e92752dec66215412f6dd3bf101f3c878b. Should be released in the next release after 2.3.13.
