### ISSUE TITLE
Hardcoded limit on events

### ISSUE THREAD

**Issue by antonsviridenko** [bluecherrydvr/bluecherry-apps-issues#88]
There is a fixed limit on the maximum number of events sent to client:
https://github.com/bluecherrydvr/bluecherry-apps/blob/master/www/events/index.php#L38

and it affects some customers
https://secure.helpscout.net/conversation/92499316/4982/

At least it should be configurable, or it is better to process database query result in small portions instead of loading everything in memory, not sure if it is possible in PHP

**Comment by curtishall** [comment]
Who are we assigning this task?  Alex isn't working on the web interface much, if at all.  @abelykh

**Comment by abelykh** [comment]
@antonsviridenko How are the events pulled into the client right now? I believe incremental pull (with starting ID parameter) was introduced into the events php a while ago.

However, the main problem with the events php afak is that xml is formed through string vars which causes apache/php to run out of memory -- which can be solved using php newer XML classes.

@antonsviridenko Could you please let me know how you think this _should_ be done from the client side, to ensure efficience (we probably dont want to do a 10,000 line join every few seconds) and I will work on resolving the other limitation.

**Comment by antonsviridenko** [comment]
>  I believe incremental pull (with starting ID parameter) was introduced into the events php a while ago.

Yes, but it is not used by client yet (parameter "afterId"). It was intended for loading new events in list below the live view area, instead of repeatedly requesting last 50 events

> Could you please let me know how you think this should be done from the client side, to ensure efficience (we probably dont want to do a 10,000 line join every few seconds) and I will work on resolving the other limitation.

Pagination, more specific search criteria. 

Possible workaround for server side can be issuing several database queries in a loop if number of events is greater than some limit (with limit/offset parameters). In this way we can send unlimited number of events using fixed amount of server memory

**Comment by antonsviridenko** [comment]
Fixed in https://github.com/bluecherrydvr/bluecherry-apps/commit/a486e2df8c4df91e54513e9bda962b1ac511eac6

Now unlimited number of events can be returned in portions, 5000 events per portion.
