### ISSUE TITLE
Web: Add controls for adjusting solo6x10 video quality

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps-issues#99]
bluechery.video_quality is currently used by the server to adjust the quality settings on the H.264 hardware compression cards.  The values are 1-31 with 1 being the best quality / highest disk usage.  

Andrey suggested a sliding bar type of UI to allow the customer to change this.

**Comment by Aleksandern** [comment]
done in issue99...I didn't edit bluecherry.cpp. I think Andrey should look at it

**Comment by ghost** [comment]
Done for v2.5.3 in ef85fd07e2b994e533416a2e6fcdc3a8de48f890 by @Aleksandern
